### ISSUE TITLE
Slight improvement suggestion for iterating globalState

### ISSUE THREAD

**Issue by tech-meppem** [robole/vscode-profile-status#7]
One of the things I've found while testing the code is it doesn't work with .code-workspace files.
You can improve that with the following change to globalState:

replace [globalState lines 57-71](https://github.com/robole/vscode-profile-status/blob/f860e34c9789a230191c8f148e1606d11a655847/src/globalState.js#L57-L71) with:
```
      //association is in form of: { workspace_uri : profile_id}
      const workspaceAssociations = obj.profileAssociations.workspaces;

      let profileID;

      let workspaceUriString = workspaceUri.toString();
      Object.keys(workspaceAssociations).every((key) => {
        const keyDir = path.basename(key).endsWith(".code-workspace") ? path.dirname(key) : key;

        if (workspaceUriString === keyDir) {
          profileID = workspaceAssociations[key];
          return false;
        }

        return true;
      });
```

Basically, if the path of the key in workspaceAssociations ends in `".code-workspace"`, then compare the dirname instead.

**Comment by robole** [comment]
hi @tech-meppem 

Thank you for the suggestion.

Its best to consider this as an experiment.  I should probably mark it as a preview in the marketplace. I outlined the limitations in the README. The API offers nothing on profiles and Microsoft have no plans to add anything (see [issue](https://github.com/microsoft/vscode/issues/208195#issuecomment-2046778283)).

I did not write this with multi-root workspaces in mind, I mentioned that in the [FAQ](https://github.com/robole/vscode-profile-status?tab=readme-ov-file#faq).  I don't think tweaking this is worthwhile really given the limitations. 

I appreciate your interest nonetheless!
